export const SKILL_OPTIONS = [
  "Furniture setup",
  "Cable management",
  "Entertainment setup",
  "Deep cleaning",
  "Gardening",
  "Grill cleaning",
  "Laundry help",
  "Decluttering",
  "Light repairs",
  "Grocery runs",
  "Meal prep",
  "Tutoring",
  "Tax help",
  "Gift shopping",
  "Tech setup",
  "Dog walking",
  "Pet grooming",
  "Pet sitting",
  "Device support",
  "Tech tutoring",
  "Game coaching",
  "Online tasks",
  "Party setup",
  "Event cleanup",
  "Catering help",
  "Packing",
  "Furniture moving",
  "Garage organizing",
  "Gift crafting",
  "Clothing fixes",
  "DIY help",
  "Item delivery",
  "Waiting in line",
  "Travel planning",
];

export const HOBBIES_OPTIONS = [
  "Reading",
  "Gardening",
  "Traveling",
  "Photography",
  "Cooking",
  "Sports",
  "Music",
  "Art",
  "Gaming",
];

export const PERSONALITIES_OPTIONS = [
  "Disciplined",
  "Reliable",
  "Focused",
  "Experienced",
  "Patient",
  "DetailOriented",
  "ProblemSolver",
  "Adaptable",
  "Collaborative",
  "Responsible",
];

export const CATEGORY_ENUM = [
  "Household Services",
  "Personal Assistant",
  "Pet Care",
  "Technology and Digital Assistance",
  "Event Support",
  "Moving and Organization",
  "Creative and Costume Tasks",
  "General Errands",
  "Other",
];

// Add other frontend constants here as needed
